name: "Deploy-dev"
on:
  push:
    branches: ["main"]
jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_DEV }}
          aws-region: ${{ secrets.REGION }}
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ secrets.DEV_STACK_NAME }} --region ${{ secrets.REGION }}
  